version: '3'
services:
  frontend:
    build:
      context: .  # Root directory, where your frontend Dockerfile is located
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://3.137.182.132:3000  # Frontend calls backend by service name

  backend:
    build:
      context: ./server  # Make sure this points to the server folder
      dockerfile: Dockerfile  # Dockerfile is inside the server folder
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://db:27017/myproject
    depends_on:
      - db  # Ensure MongoDB starts before backend

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
