version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming the frontend Dockerfile is in the root directory
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server  # Set the context to the server folder
      dockerfile: Dockerfile
    volumes:
      - ./server:/app  # Mount the server folder into the container
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/myproject  # MongoDB connection
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

volumes:
  mongo-data:
