version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile # Points to the frontend Dockerfile in the root directory
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server  # Points to the backend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://db:27017/myproject

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
